version: "3.8"
services:
  db:
    image: postgres
    container_name: local_postgresdb
    restart: always
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: ingsw
      POSTGRES_PASSWORD: administrator
      POSTGRES_DB: postgres
    volumes:
     - ./sql/NewDb.sql:/docker-entrypoint-initdb.d/create_tables.sql
     - ./sql/NewQueries.sql:/docker-entrypoint-initdb.d/fill_tables.sql
     - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ingsw@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin

  
  java_app:
     build:
       context: .
       dockerfile: Dockerfile.txt
     container_name: java_app_container
     restart: always
     ports:
       - "8080:8080"
     depends_on:
       - db  # Garantisce che il servizio Java aspetti che il servizio db sia pronto
     environment:
       DATABASE_URL: jdbc:postgresql://localhost:5432/postgres
       DATABASE_USER: ingsw
       DATABASE_PASSWORD: administrator

volumes:
  local_pgdata:
  pgadmin-data:

